VCF4.3 to VCF4.4 change list
samtools/hts-specs pull request #653
Opened 2022-06-15 09:50 UTC by tcezard

I was asked to summarise the changes introduced between 4.3 and 4.4 and though I might as well add it here. 
I also added the change list between 4.1 and 4.2 for completeness

2022-06-20 05:34 UTC, d-cameron requested changes
Sorry about the delay in reviewing.

2022-06-21 14:03 UTC, tcezard commented on VCFv4.3.tex
> +\begin{itemize}
I missed that. Thank you.

2022-06-21 14:03 UTC, tcezard commented on VCFv4.4.draft.tex
> +\item Define new reserved INFO field EVENT, EVENTTYPE and SVCLAIM
Added.

2022-06-21 14:03 UTC, tcezard commented on VCFv4.4.draft.tex
> +\item Clarify how to add multiple SV per record by making the number of value in reserved SV INFO fields dependent on the number of ALT
Added

2022-08-16 14:35 UTC, merged